CREATE SCHEMA IF NOT EXISTS public;

--SERIES
CREATE TABLE IF NOT EXISTS public.series (
  series_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_name   TEXT NOT NULL,
  volume        INTEGER,
  publisher     TEXT NOT NULL
);

ALTER TABLE public.series
  ADD CONSTRAINT uq_series_name_vol UNIQUE (series_name, volume, publisher);

--CREATORS
CREATE TABLE IF NOT EXISTS public.creators (
  creator_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  primary_role  TEXT,
  active        BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE public.creators
 ADD CONSTRAINT uq_creators_name UNIQUE (name);

CREATE INDEX IF NOT EXISTS idx_creators_name
  ON public.creators (lower(name));

--COMICS
CREATE TABLE IF NOT EXISTS public.comics (
  comic_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id           BIGINT NOT NULL,
  title               TEXT,
  issue               INTEGER NOT NULL,
  release_date        DATE,
  cover_month         TEXT,
  cover_year          INTEGER,
  cover_price         NUMERIC(10,2),
  upc                 TEXT,
  is_variant          BOOLEAN NOT NULL DEFAULT FALSE,
  variant_name        TEXT,
  variant_artist_id   BIGINT,
  is_incentive        BOOLEAN NOT NULL DEFAULT FALSE,
  incentive_ratio     TEXT,
  CONSTRAINT fk_comics_series
    FOREIGN KEY (series_id) REFERENCES public.series(series_id)ON DELETE CASCADE,
 CONSTRAINT fk_comics_variant_artist
   FOREIGN KEY (variant_artist_id) REFERENCES public.creators(creator_id) ON DELETE SET NULL
  --,CONSTRAINT uq_comics_upc UNIQUE (upc)
);

CREATE INDEX IF NOT EXISTS idx_comics_series_id ON public.comics(series_id);
--CREATE INDEX IF NOT EXISTS idx_comics_upc       ON public.comics(upc);

--COMIC CREATORS
CREATE TABLE IF NOT EXISTS public.comic_creators (
  comic_creator_id BIGSERIAL PRIMARY KEY,
  comic_id   BIGINT NOT NULL,
  creator_id BIGINT NOT NULL,
  role_on_issue TEXT,
  FOREIGN KEY (comic_id)   REFERENCES public.comics(comic_id),
  FOREIGN KEY (creator_id) REFERENCES public.creators(creator_id)
);

CREATE INDEX IF NOT EXISTS idx_cc_creator ON public.comic_creators(creator_id);