CREATE SCHEMA IF NOT EXISTS public;

--STOCK ITEMS
CREATE TABLE IF NOT EXISTS public.stock_items (
  stock_item_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comic_id        BIGINT NOT NULL,
  num_in_stock    INTEGER NOT NULL DEFAULT 0,
  num_ordered     INTEGER NOT NULL DEFAULT 0,
  num_reserved    INTEGER NOT NULL DEFAULT 0,
  list_price      NUMERIC(10,2),
  for_sale        BOOLEAN NOT NULL DEFAULT TRUE,
  item_notes      TEXT,
  created_on      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_updated    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE INDEX IF NOT EXISTS idx_stock_items_comic_id ON public.stock_items(comic_id);
CREATE INDEX IF NOT EXISTS idx_stock_items_for_sale  ON public.stock_items(for_sale);

--STOCK UPDATE
CREATE TABLE IF NOT EXISTS public.stock_updates (
  stock_update_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_item_id   BIGINT NOT NULL,
  update_type     TEXT   NOT NULL,
  quantity_delta  INTEGER NOT NULL,
  prev_quantity   INTEGER NOT NULL,
  new_quantity    INTEGER NOT NULL,
  created_date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_notes    TEXT,
  CONSTRAINT fk_stock_updates_item
    FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(stock_item_id) ON DELETE CASCADE,
  CONSTRAINT ck_stock_updates_type CHECK (
    update_type IN (
      'SALE','RESTOCK','RETURN','CORRECTION',
      'PRICE_DROP','PRICE_INCREASE','DAMAGE',
      'THEFT','ITEM_LOST','ADD_NOTE'
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_stock_updates_item_id ON public.stock_updates(stock_item_id);
CREATE INDEX IF NOT EXISTS idx_stock_updates_type    ON public.stock_updates(update_type);
CREATE INDEX IF NOT EXISTS idx_stock_updates_created ON public.stock_updates(created_date);

